CREATE SCHEMA IF NOT EXISTS interacao_scala_postgre;

-- Banco transacional que simula a origem dos dados do ETL.
CREATE TABLE IF NOT EXISTS interacao_scala_postgre.Interacao (
    PkInteracao bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NomeUsuario varchar(100) NOT NULL
        CHECK (btrim(NomeUsuario) <> ''),
    DataInsercao timestamp without time zone NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    DataAtualizacao timestamp without time zone NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    Mensagem text NOT NULL,
    Tier smallint NOT NULL
        CHECK (Tier IN (1, 2, 3)),
    RendaMensal numeric(14, 2)
        CHECK (RendaMensal >= 0)
);

-- Atualiza instalações criadas antes de RendaMensal existir.
ALTER TABLE interacao_scala_postgre.Interacao
    ADD COLUMN IF NOT EXISTS RendaMensal numeric(14, 2)
        CHECK (RendaMensal >= 0);

CREATE TABLE IF NOT EXISTS interacao_scala_postgre.InteracaoHistorico (
    PkInteracaoHistorico bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FkInteracao bigint NOT NULL
        REFERENCES interacao_scala_postgre.Interacao(PkInteracao),
    DataInsercao timestamp without time zone NOT NULL
        DEFAULT CURRENT_TIMESTAMP,
    TierAnterior smallint NOT NULL
        CHECK (TierAnterior IN (1, 2, 3)),
    TierNovo smallint NOT NULL
        CHECK (TierNovo IN (1, 2, 3)),
    CONSTRAINT InteracaoHistoricoTierAlterado
        CHECK (TierAnterior <> TierNovo)
);

CREATE INDEX IF NOT EXISTS IX_InteracaoHistorico_FkInteracao
    ON interacao_scala_postgre.InteracaoHistorico(FkInteracao);
